// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvjxgxuzpcciaspztupn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2anhneHV6cGNjaWFzcHp0dXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjcxODcsImV4cCI6MjA2MDg0MzE4N30.YOroAPSRaCiRkzhYlxYciPR_OfgKS2iTd26HVzVq6yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);